### ISSUE TITLE
last ha update seems to break the integration

### ISSUE THREAD

**Issue by cob94440** [rospogrigio/daikin_residential#90]
Hi,

Last version of ha seems to do something with daikin integration. it was ok before update. now it doesnt see my climate

**Comment by droscy** [comment]
Hi @cob94440, I don't know your error neither your setup, but since version 2022.7 Home Assistant ships with python 3.10 for main installation methods (see official [Breaking Changes](https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes)) and older daikin_residential versions requires package `oic` _v1.2.1_ which is incompatible with python 3.10.

If this is your case you should see an error in HA logs like

    ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

Simply upgrade daikin_residential to have `oic` v1.4.0 installed and the error should disappear.

**Comment by droscy** [comment]
Hi @cob94440, did you solve?
